# Generated by Django 6.0 on 2026-01-23 23:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chauffeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_permis', models.CharField(max_length=20, unique=True)),
                ('nom_chauffeur', models.CharField(max_length=100)),
                ('prenom_chauffeur', models.CharField(max_length=100)),
                ('adresse_chauffeur', models.TextField()),
                ('statut_chauffeur', models.CharField(choices=[('disponible', 'disponible'), ('non_disponible', 'non disponible')], default='disponible', max_length=20)),
                ('email_chauffeur', models.EmailField(max_length=254, unique=True)),
                ('tel_chauffeur', models.CharField(max_length=10)),
                ('categ_permis', models.CharField(max_length=20)),
                ('date_embauchement', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_client', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(max_length=20)),
                ('adresse', models.TextField()),
                ('solde', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_destination', models.CharField(max_length=50, unique=True)),
                ('pays_dest', models.CharField(max_length=50)),
                ('ville_dest', models.CharField(max_length=50)),
                ('zone_geographique', models.CharField(max_length=50)),
                ('tarif_base', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='TypeDeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_service', models.CharField(max_length=20, unique=True)),
                ('nom_service', models.CharField(choices=[('standard', 'Standard'), ('express', 'Express'), ('international', 'International')], max_length=50)),
                ('description_service', models.TextField(blank=True)),
                ('delai_estime', models.PositiveIntegerField(help_text='Délai estimé en jours')),
                ('coefficient_service', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(max_length=20, unique=True)),
                ('type_vehicule', models.CharField(max_length=50)),
                ('capacite_kg', models.FloatField()),
                ('consommation_litre_100km', models.FloatField()),
                ('etat_vehicule', models.CharField(choices=[('disponible', 'Disponible'), ('en_panne', 'En panne'), ('en_tournee', 'En tournée')], default='disponible', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Expedition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking', models.CharField(editable=False, max_length=50, unique=True)),
                ('statut_expedition', models.CharField(choices=[('cree', 'Crée'), ('transit', 'En transit'), ('tri', 'En centre de tri'), ('livraison', 'En cours de livraison'), ('livree', 'Livrée'), ('echec', 'Echec de livraison')], default='cree', max_length=20)),
                ('date_creation_exp', models.DateTimeField(auto_now_add=True)),
                ('description_exp', models.TextField(blank=True, null=True)),
                ('montant_expedition', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expeditions', to='core.client')),
            ],
        ),
        migrations.CreateModel(
            name='Colis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_colis', models.CharField(max_length=50, unique=True)),
                ('poids_colis', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volume_colis', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description_colis', models.TextField()),
                ('expedition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colis', to='core.expedition', to_field='tracking')),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_facture', models.CharField(max_length=20, unique=True)),
                ('date_facture', models.DateField(auto_now_add=True)),
                ('montant_HT', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('montant_TVA', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('montant_TTC', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('statut_facture', models.CharField(choices=[('non_payee', 'Non payée'), ('partielle', 'Partiellement payée'), ('payee', 'Payée')], default='non_payee', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='core.client')),
            ],
        ),
        migrations.AddField(
            model_name='expedition',
            name='facture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expeditions', to='core.facture'),
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_paiement', models.CharField(max_length=50, unique=True)),
                ('mode_paiement', models.CharField(max_length=50)),
                ('date_paiement', models.DateField()),
                ('montant_paiement', models.DecimalField(decimal_places=2, max_digits=10)),
                ('client', models.ForeignKey(db_column='id_client_id', on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='core.client')),
                ('facture', models.ForeignKey(db_column='id_facture_id', on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='core.facture')),
            ],
        ),
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_reclamation', models.CharField(max_length=20, unique=True)),
                ('nature_reclamation', models.CharField(max_length=150)),
                ('date_reclamation', models.DateField(auto_now_add=True)),
                ('date_resolution', models.DateField(blank=True, null=True)),
                ('etat_reclamation', models.CharField(choices=[('en_cours', 'en cours de traitement'), ('resolue', 'résolue'), ('annulee', 'annulée')], default='en_cours', max_length=20)),
                ('agent_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamations', to='core.client')),
                ('expedition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reclamations', to='core.expedition', to_field='tracking')),
                ('facture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reclamations', to='core.facture')),
                ('type_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reclamations', to='core.typedeservice')),
            ],
        ),
        migrations.CreateModel(
            name='ColisReclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colis_reclamations', to='core.colis')),
                ('reclamation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colis_reclamations', to='core.reclamation')),
            ],
        ),
        migrations.CreateModel(
            name='SuiviExpedition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_suivi', models.CharField(editable=False, max_length=20, unique=True)),
                ('date_passage', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('cree', 'Crée'), ('transit', 'En transit'), ('tri', 'En centre de tri'), ('livraison', 'En cours de livraison'), ('livree', 'Livrée'), ('echec', 'Echec de livraison')], default='cree', max_length=20)),
                ('lieu_passage', models.CharField(max_length=50)),
                ('commentaire', models.TextField()),
                ('suivi_expedition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivi', to='core.expedition', to_field='tracking')),
            ],
        ),
        migrations.CreateModel(
            name='Tarification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarif_poids', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tarif_volume', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tarif_final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifications', to='core.destination')),
                ('type_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifications', to='core.typedeservice')),
            ],
        ),
        migrations.AddField(
            model_name='expedition',
            name='tarification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expeditions', to='core.tarification'),
        ),
        migrations.CreateModel(
            name='Tournee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tournee', models.CharField(max_length=20, unique=True)),
                ('date_tournee', models.DateField()),
                ('kilometrage', models.FloatField()),
                ('duree', models.PositiveIntegerField(help_text='duree de la tournee par heurs')),
                ('note', models.TextField(blank=True, null=True)),
                ('chauffeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tournees', to='core.chauffeur')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tournees', to='core.vehicule')),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_incident', models.CharField(max_length=20, unique=True)),
                ('type_incident', models.CharField(max_length=100)),
                ('date_incident', models.DateField()),
                ('description_incident', models.TextField()),
                ('colis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='core.colis')),
                ('expedition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='core.expedition', to_field='tracking')),
                ('tournee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='core.tournee')),
            ],
        ),
        migrations.AddField(
            model_name='expedition',
            name='tournee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expeditions', to='core.tournee'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('AGENT', 'Agent'), ('RESP', 'Responsable')], max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
