# Generated by Django 6.0 on 2026-02-02 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarification',
            name='tarif_final',
        ),
    ]
