# Generated by Django 6.0 on 2026-01-08 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colis',
            name='statue_colis',
        ),
        migrations.AddField(
            model_name='suiviexpedition',
            name='statut',
            field=models.CharField(choices=[('cree', 'Crée'), ('transit', 'En transit'), ('tri', 'En centre de tri'), ('livraison', 'En cours de livraison'), ('livree', 'Livrée'), ('echec', 'Echec de livraison')], default=0.0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='suiviexpedition',
            name='id_suivi',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
