# Generated by Django 6.0 on 2026-01-07 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='type_incident',
            field=models.CharField(choices=[('retard', 'Retard'), ('perte', 'Perte'), ('endommagement', 'Endommagement'), ('probleme_technique', 'Problème technique')], max_length=30),
        ),
    ]
