# Generated by Django 6.0 on 2025-12-29 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='id_client',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_reclamation', models.CharField(max_length=20, unique=True)),
                ('nature_reclamation', models.CharField(max_length=150)),
                ('date_reclamation', models.DateField(auto_now_add=True)),
                ('etat_reclamation', models.CharField(default='En cours', max_length=50)),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamations', to='core.client')),
            ],
        ),
    ]
