# Generated by Django 6.0 on 2026-01-24 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_incident_type_incident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='montant_HT',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='facture',
            name='montant_TTC',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='facture',
            name='montant_TVA',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='mode_paiement',
            field=models.CharField(choices=[('Especes', 'Espèces'), ('Carte', 'Carte bancaire'), ('Virement', 'Virement'), ('Cheque', 'Chèque')], max_length=20),
        ),
    ]
