# Generated by Django 6.0 on 2025-12-30 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_expedition_facture_expedition_tarification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='core.userprofile'),
        ),
    ]
