# Generated by Django 6.0 on 2025-12-29 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_client_id_client_reclamation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='id_client',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
