# Generated by Django 6.0 on 2026-01-23 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_reclamation_agent_responsable_reclamation_facture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colis',
            name='statue_colis',
        ),
        migrations.AddField(
            model_name='reclamation',
            name='date_resolution',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suiviexpedition',
            name='statut',
            field=models.CharField(choices=[('cree', 'Crée'), ('transit', 'En transit'), ('tri', 'En centre de tri'), ('livraison', 'En cours de livraison'), ('livree', 'Livrée'), ('echec', 'Echec de livraison')], default='cree', max_length=20),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='agent_responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='suiviexpedition',
            name='id_suivi',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
