# Generated by Django 6.0 on 2026-02-02 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_reclamation_date_reclamation_and_more'),
        ('core', '0002_remove_tarification_tarif_final'),
    ]

    operations = [
    ]
