# Generated by Django 6.0 on 2026-01-23 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_colis_statue_colis_suiviexpedition_statut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='client',
            field=models.ForeignKey(db_column='id_client_id', on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='core.client'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='facture',
            field=models.ForeignKey(db_column='id_facture_id', on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='core.facture'),
        ),
    ]
