# Generated by Django 6.0 on 2026-01-23 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_paiement_client_alter_paiement_facture'),
    ]

    operations = [
    ]
