# Generated by Django 6.0 on 2025-12-31 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_facture_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='colis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='core.colis', to_field='id_colis'),
        ),
    ]
