# Generated by Django 6.0 on 2025-12-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_client_id_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chauffeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_permis', models.CharField(max_length=20, unique=True)),
                ('nom_chauffeur', models.CharField(max_length=100)),
                ('prenom_chauffeur', models.CharField(max_length=100)),
                ('adresse_chauffeur', models.TextField()),
                ('statut_chauffeur', models.CharField(max_length=50)),
                ('email_chauffeur', models.EmailField(max_length=254, unique=True)),
                ('tel_chauffeur', models.CharField(max_length=10)),
                ('categ_permis', models.CharField(max_length=20)),
                ('date_embauchement', models.DateField()),
            ],
        ),
    ]
