# Generated by Django 6.0 on 2025-12-31 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_incident_colis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expedition',
            name='user',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='user',
        ),
        migrations.AlterField(
            model_name='expedition',
            name='description_exp',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='montant_expedition',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='tarification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expeditions', to='core.tarification'),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='tracking',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='colis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='core.colis'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='expedition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='core.expedition'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='tournee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='core.tournee'),
        ),
        migrations.AlterField(
            model_name='tarification',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifications', to='core.destination'),
        ),
        migrations.AlterField(
            model_name='tarification',
            name='type_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifications', to='core.typedeservice'),
        ),
        migrations.AlterField(
            model_name='tournee',
            name='chauffeur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournees', to='core.chauffeur'),
        ),
        migrations.AlterField(
            model_name='tournee',
            name='vehicule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournees', to='core.vehicule'),
        ),
    ]
