# Generated by Django 6.0 on 2026-01-01 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_expedition_user_remove_facture_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colis',
            name='expedition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colis', to='core.expedition', to_field='tracking'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='colis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='core.colis'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='expedition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='core.expedition', to_field='tracking'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='tournee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='core.tournee'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='expedition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reclamations', to='core.expedition', to_field='tracking'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='type_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reclamations', to='core.typedeservice'),
        ),
        migrations.AlterField(
            model_name='suiviexpedition',
            name='suivi_expedition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivi', to='core.expedition', to_field='tracking'),
        ),
        migrations.AlterField(
            model_name='tournee',
            name='chauffeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tournees', to='core.chauffeur'),
        ),
        migrations.AlterField(
            model_name='tournee',
            name='vehicule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tournees', to='core.vehicule'),
        ),
    ]
