# Generated by Django 6.0 on 2025-12-29 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_expedition'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expedition',
        ),
    ]
