# Generated by Django 6.0 on 2026-01-01 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_colis_expedition_alter_incident_colis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedition',
            name='facture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expeditions', to='core.facture'),
        ),
    ]
