# Generated by Django 6.0 on 2025-12-29 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_expedition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expedition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_expedition', models.CharField(max_length=50, unique=True)),
                ('statut_expedition', models.CharField(choices=[('cree', 'Crée'), ('transit', 'En transit'), ('tri', 'En centre de tri'), ('livraison', 'En cours de livraison'), ('livre', 'Livré'), ('echec', 'Echec de livraison')], default='cree', max_length=20)),
                ('date_creation_exp', models.DateTimeField(auto_now_add=True)),
                ('description_exp', models.TextField()),
                ('montant_expedition', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expeditions', to='core.client')),
            ],
        ),
    ]
