# Generated by Django 6.0 on 2026-01-02 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_colis_expedition_alter_incident_colis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='montant_HT',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='facture',
            name='montant_TTC',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='facture',
            name='montant_TVA',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
