# Generated by Django 6.0 on 2026-01-01 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_expedition_facture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedition',
            name='facture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expeditions', to='core.facture'),
        ),
    ]
