# Generated by Django 6.0 on 2025-12-29 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_expedition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chauffeur',
            name='statut_chauffeur',
        ),
        migrations.RemoveField(
            model_name='reclamation',
            name='etat_reclamation',
        ),
    ]
