# Generated by Django 6.0 on 2025-12-29 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_chauffeur_statut_chauffeur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chauffeur',
            name='statut_chauffeur',
            field=models.CharField(choices=[('disponible', 'disponible'), ('non_disponible', 'non disponible')], default='disponible', max_length=20),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='etat_reclamation',
            field=models.CharField(choices=[('en_cours', 'en cours de traitement'), ('resolue', 'résolue'), ('annulee', 'annulée')], default='en_cours', max_length=20),
        ),
    ]
