# Generated by Django 6.0 on 2026-01-02 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_facture_montant_ht_alter_facture_montant_ttc_and_more'),
        ('core', '0008_alter_expedition_facture'),
    ]

    operations = [
    ]
