# Generated by Django 6.0 on 2025-12-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_chauffeur_statut_chauffeur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedition',
            name='statut_expedition',
            field=models.CharField(choices=[('cree', 'Crée'), ('transit', 'En transit'), ('tri', 'En centre de tri'), ('livraison', 'En cours de livraison'), ('livree', 'Livrée'), ('echec', 'Echec de livraison')], default='cree', max_length=20),
        ),
    ]
