# Generated by Django 6.0 on 2025-12-29 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_expedition_statut_expedition'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeDeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_service', models.CharField(max_length=20, unique=True)),
                ('nom_service', models.CharField(choices=[('standard', 'Standard'), ('express', 'Express'), ('international', 'International')], max_length=50)),
                ('description_service', models.TextField(blank=True)),
                ('delai_estime', models.PositiveIntegerField(help_text='Délai estimé en jours')),
                ('CoefficientService', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(max_length=20, unique=True)),
                ('type_vehicule', models.CharField(max_length=50)),
                ('capacite_kg', models.FloatField()),
                ('consommation_litre_100km', models.FloatField()),
                ('etat_vehicule', models.CharField(choices=[('disponible', 'Disponible'), ('en_panne', 'En panne'), ('en_tournee', 'En tournée')], default='disponible', max_length=20)),
            ],
        ),
    ]
