# Generated by Django 6.0 on 2025-12-29 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_typedeservice_vehicule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expedition',
            old_name='num_expedition',
            new_name='Tracking',
        ),
        migrations.AddField(
            model_name='reclamation',
            name='Expedition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations', to='core.expedition'),
        ),
    ]
