# Generated by Django 6.0 on 2025-12-29 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_num_expedition_expedition_tracking_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expedition',
            old_name='date_creation_exp',
            new_name='Date_creation_exp',
        ),
        migrations.RenameField(
            model_name='expedition',
            old_name='description_exp',
            new_name='Description_exp',
        ),
        migrations.RenameField(
            model_name='expedition',
            old_name='montant_expedition',
            new_name='Montant_expedition',
        ),
        migrations.RenameField(
            model_name='expedition',
            old_name='statut_expedition',
            new_name='Statut_expedition',
        ),
        migrations.RenameField(
            model_name='reclamation',
            old_name='Expedition',
            new_name='Tracking_Expedition',
        ),
    ]
