# Generated by Django 6.0 on 2025-12-29 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_date_creation_exp_expedition_date_creation_exp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_facture', models.CharField(max_length=20, unique=True)),
                ('date_facture', models.DateField(auto_now_add=True)),
                ('montant_HT', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_TVA', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_TTC', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut_facture', models.CharField(choices=[('non_payee', 'Non payée'), ('partielle', 'Partiellement payée'), ('payee', 'Payée')], default='non_payee', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='core.client')),
            ],
        ),
        migrations.CreateModel(
            name='suiviExpedition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_suivi', models.CharField(max_length=20, unique=True)),
                ('date_passage', models.DateTimeField(auto_now_add=True)),
                ('lieu_passage', models.CharField(max_length=50)),
                ('commentaire', models.TextField()),
                ('suivi_expedition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivi', to='core.expedition')),
            ],
        ),
    ]
