# Generated by Django 6.0 on 2025-12-29 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_date_creation_exp_expedition_date_creation_exp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expedition',
            old_name='id_client',
            new_name='Client',
        ),
        migrations.RenameField(
            model_name='reclamation',
            old_name='id_client',
            new_name='Client',
        ),
        migrations.RenameField(
            model_name='reclamation',
            old_name='Tracking_Expedition',
            new_name='Expedition',
        ),
        migrations.CreateModel(
            name='Tournee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tournee', models.CharField(max_length=20, unique=True)),
                ('date_tournee', models.DateField()),
                ('kilometrage', models.FloatField()),
                ('duree', models.PositiveIntegerField(help_text='duree de la tournee par heurs')),
                ('note', models.TextField(blank=True, null=True)),
                ('chauffeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.chauffeur', to_field='num_permis')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vehicule', to_field='immatriculation')),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_incident', models.CharField(max_length=20, unique=True)),
                ('type_incident', models.CharField(max_length=100)),
                ('date_incident', models.DateField()),
                ('description_incident', models.TextField()),
                ('expedition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.expedition', to_field='Tracking')),
                ('tournee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tournee', to_field='id_tournee')),
            ],
        ),
    ]
