# Generated by Django 6.0 on 2025-12-30 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_facture_suiviexpedition'),
        ('core', '0014_rename_id_client_expedition_client_and_more'),
    ]

    operations = [
    ]
