# Generated by Django 6.0 on 2025-12-30 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_merge_20251230_0117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_destination', models.CharField(max_length=50, unique=True)),
                ('pays_dest', models.CharField(max_length=50)),
                ('ville_dest', models.CharField(max_length=50)),
                ('zone_geographique', models.CharField(max_length=50)),
                ('tarif_base', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Colis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_colis', models.CharField(max_length=50, unique=True)),
                ('poids_colis', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volume_colis', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description_colis', models.TextField()),
                ('statue_colis', models.CharField(max_length=50)),
                ('num_expedition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colis', to='core.expedition')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_paiement', models.CharField(max_length=50, unique=True)),
                ('mode_paiement', models.CharField(max_length=50)),
                ('date_paiement', models.DateField()),
                ('montant_paiement', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='core.client')),
                ('id_facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='core.facture')),
            ],
        ),
        migrations.CreateModel(
            name='Tarification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarif_poids', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tarif_volume', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tarif_final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.destination')),
                ('id_typeService', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.typedeservice')),
            ],
        ),
    ]
